{
# 公众号配置
# 公众号appId
"app_id": "wx7586364c6ad6dcfa",
# 公众号appSecret
"app_secret": "0767f7fa9ca72b974484ed6088a206a6",
# 模板消息id
"template_id": "CoGCJjmw5E0Jkaux3H6_XFJkZ17-AjZoEneI53cRKa8",
# 接收公众号消息的微信号，如果有多个，需要在[]里用英文逗号间隔，例如["wx1", "wx2"]
"user": ["oNPt75j-U66b4gn7u7d6Kvg3ZOfE"],
 
# 信息配置
# 和风天气apikey
"weather_key": "4575f0bd30f24692a9e772ec2389452f",
# 所在地区，可为省，城市，区，县，同时支持国外城市，例如伦敦
"region": "泊头市",
# 生日1，修改名字为对应需要显示的名字，如果生日为农历，在最前面加上r即可
"birthday1": {"name": "哥哥", "birthday": "2001-10-10"},
# 生日2
"birthday2": {"name": "杨八九", "birthday": "2001-11-09"},
# 在一起的日子，格式同上，暂不不支持农历
"love_date": "2022-10-18",
# 金句中文，如果设置了，则会显示这里的，如果为空，默认会读取金山的每日金句
"note_ch": "",
# 金句英文
"note_en": ""
}
